# Generated by Django 5.1.5 on 2025-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinas', models.CharField(max_length=10, unique=True)),
                ('sigla', models.CharField(max_length=255)),
                ('curso', models.TextField(blank=True, null=True)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('semestre', models.PositiveIntegerField()),
                ('professor_responsavel', models.CharField(max_length=255)),
            ],
        ),
    ]
